// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 V2_Thumbstick
        {
            get
            {
                return SteamVR_Actions.default_V2_Thumbstick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ButtonA
        {
            get
            {
                return SteamVR_Actions.default_Bool_ButtonA;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ButtonB
        {
            get
            {
                return SteamVR_Actions.default_Bool_ButtonB;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ButtonX
        {
            get
            {
                return SteamVR_Actions.default_Bool_ButtonX;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ButtonY
        {
            get
            {
                return SteamVR_Actions.default_Bool_ButtonY;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ThumbstickUp
        {
            get
            {
                return SteamVR_Actions.default_Bool_ThumbstickUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ThumbstickDown
        {
            get
            {
                return SteamVR_Actions.default_Bool_ThumbstickDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ThumbstickLeft
        {
            get
            {
                return SteamVR_Actions.default_Bool_ThumbstickLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ThumbstickRight
        {
            get
            {
                return SteamVR_Actions.default_Bool_ThumbstickRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_Trigger
        {
            get
            {
                return SteamVR_Actions.default_Bool_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_Grip
        {
            get
            {
                return SteamVR_Actions.default_Bool_Grip;
            }
        }
        
        public virtual SteamVR_Action_Single V1_Trigger
        {
            get
            {
                return SteamVR_Actions.default_V1_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Single V1_Grip
        {
            get
            {
                return SteamVR_Actions.default_V1_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ButtonThumbstick
        {
            get
            {
                return SteamVR_Actions.default_Bool_ButtonThumbstick;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
