// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 V2_LeftThumbstick
        {
            get
            {
                return SteamVR_Actions.default_V2_LeftThumbstick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 V2_RightThumbstick
        {
            get
            {
                return SteamVR_Actions.default_V2_RightThumbstick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ButtonA
        {
            get
            {
                return SteamVR_Actions.default_Bool_ButtonA;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ButtonB
        {
            get
            {
                return SteamVR_Actions.default_Bool_ButtonB;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ButtonX
        {
            get
            {
                return SteamVR_Actions.default_Bool_ButtonX;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_ButtonY
        {
            get
            {
                return SteamVR_Actions.default_Bool_ButtonY;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_LThumbstickUp
        {
            get
            {
                return SteamVR_Actions.default_Bool_LThumbstickUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_LThumbstickDown
        {
            get
            {
                return SteamVR_Actions.default_Bool_LThumbstickDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_LThumbstickLeft
        {
            get
            {
                return SteamVR_Actions.default_Bool_LThumbstickLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_LThumbstickRight
        {
            get
            {
                return SteamVR_Actions.default_Bool_LThumbstickRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_RThumbstickUp
        {
            get
            {
                return SteamVR_Actions.default_Bool_RThumbstickUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_RThumbstickDown
        {
            get
            {
                return SteamVR_Actions.default_Bool_RThumbstickDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_RThumbstickLeft
        {
            get
            {
                return SteamVR_Actions.default_Bool_RThumbstickLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_RThumbstickRight
        {
            get
            {
                return SteamVR_Actions.default_Bool_RThumbstickRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_LTrigger
        {
            get
            {
                return SteamVR_Actions.default_Bool_LTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_LGrip
        {
            get
            {
                return SteamVR_Actions.default_Bool_LGrip;
            }
        }
        
        public virtual SteamVR_Action_Single V1_LTrigger
        {
            get
            {
                return SteamVR_Actions.default_V1_LTrigger;
            }
        }
        
        public virtual SteamVR_Action_Single V1_LGrip
        {
            get
            {
                return SteamVR_Actions.default_V1_LGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_RTrigger
        {
            get
            {
                return SteamVR_Actions.default_Bool_RTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Bool_RGrip
        {
            get
            {
                return SteamVR_Actions.default_Bool_RGrip;
            }
        }
        
        public virtual SteamVR_Action_Single V1_RTrigger
        {
            get
            {
                return SteamVR_Actions.default_V1_RTrigger;
            }
        }
        
        public virtual SteamVR_Action_Single V1_RGrip
        {
            get
            {
                return SteamVR_Actions.default_V1_RGrip;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
