// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Vector2 p_default_V2_Thumbstick;
        
        private static SteamVR_Action_Boolean p_default_Bool_ButtonA;
        
        private static SteamVR_Action_Boolean p_default_Bool_ButtonB;
        
        private static SteamVR_Action_Boolean p_default_Bool_ButtonX;
        
        private static SteamVR_Action_Boolean p_default_Bool_ButtonY;
        
        private static SteamVR_Action_Boolean p_default_Bool_ThumbstickUp;
        
        private static SteamVR_Action_Boolean p_default_Bool_ThumbstickDown;
        
        private static SteamVR_Action_Boolean p_default_Bool_ThumbstickLeft;
        
        private static SteamVR_Action_Boolean p_default_Bool_ThumbstickRight;
        
        private static SteamVR_Action_Boolean p_default_Bool_Trigger;
        
        private static SteamVR_Action_Boolean p_default_Bool_Grip;
        
        private static SteamVR_Action_Single p_default_V1_Trigger;
        
        private static SteamVR_Action_Single p_default_V1_Grip;
        
        private static SteamVR_Action_Boolean p_default_Bool_ButtonThumbstick;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy <SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy <SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy <SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_V2_Thumbstick
        {
            get
            {
                return SteamVR_Actions.p_default_V2_Thumbstick.GetCopy <SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_ButtonA
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_ButtonA.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_ButtonB
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_ButtonB.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_ButtonX
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_ButtonX.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_ButtonY
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_ButtonY.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_ThumbstickUp
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_ThumbstickUp.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_ThumbstickDown
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_ThumbstickDown.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_ThumbstickLeft
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_ThumbstickLeft.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_ThumbstickRight
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_ThumbstickRight.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_Trigger
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_Trigger.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_Grip
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_Grip.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single default_V1_Trigger
        {
            get
            {
                return SteamVR_Actions.p_default_V1_Trigger.GetCopy <SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single default_V1_Grip
        {
            get
            {
                return SteamVR_Actions.p_default_V1_Grip.GetCopy <SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Bool_ButtonThumbstick
        {
            get
            {
                return SteamVR_Actions.p_default_Bool_ButtonThumbstick.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy <SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[]
            {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_V2_Thumbstick,
                    SteamVR_Actions.default_Bool_ButtonA,
                    SteamVR_Actions.default_Bool_ButtonB,
                    SteamVR_Actions.default_Bool_ButtonX,
                    SteamVR_Actions.default_Bool_ButtonY,
                    SteamVR_Actions.default_Bool_ThumbstickUp,
                    SteamVR_Actions.default_Bool_ThumbstickDown,
                    SteamVR_Actions.default_Bool_ThumbstickLeft,
                    SteamVR_Actions.default_Bool_ThumbstickRight,
                    SteamVR_Actions.default_Bool_Trigger,
                    SteamVR_Actions.default_Bool_Grip,
                    SteamVR_Actions.default_V1_Trigger,
                    SteamVR_Actions.default_V1_Grip,
                    SteamVR_Actions.default_Bool_ButtonThumbstick,
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_V2_Thumbstick,
                    SteamVR_Actions.default_Bool_ButtonA,
                    SteamVR_Actions.default_Bool_ButtonB,
                    SteamVR_Actions.default_Bool_ButtonX,
                    SteamVR_Actions.default_Bool_ButtonY,
                    SteamVR_Actions.default_Bool_ThumbstickUp,
                    SteamVR_Actions.default_Bool_ThumbstickDown,
                    SteamVR_Actions.default_Bool_ThumbstickLeft,
                    SteamVR_Actions.default_Bool_ThumbstickRight,
                    SteamVR_Actions.default_Bool_Trigger,
                    SteamVR_Actions.default_Bool_Grip,
                    SteamVR_Actions.default_V1_Trigger,
                    SteamVR_Actions.default_V1_Grip,
                    SteamVR_Actions.default_Bool_ButtonThumbstick};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[]
            {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[]
            {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[]
            {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[]
            {
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_Bool_ButtonA,
                    SteamVR_Actions.default_Bool_ButtonB,
                    SteamVR_Actions.default_Bool_ButtonX,
                    SteamVR_Actions.default_Bool_ButtonY,
                    SteamVR_Actions.default_Bool_ThumbstickUp,
                    SteamVR_Actions.default_Bool_ThumbstickDown,
                    SteamVR_Actions.default_Bool_ThumbstickLeft,
                    SteamVR_Actions.default_Bool_ThumbstickRight,
                    SteamVR_Actions.default_Bool_Trigger,
                    SteamVR_Actions.default_Bool_Grip,
                    SteamVR_Actions.default_Bool_ButtonThumbstick};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[]
            {
                    SteamVR_Actions.default_V1_Trigger,
                    SteamVR_Actions.default_V1_Grip};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[]
            {
                    SteamVR_Actions.default_V2_Thumbstick};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[]
            {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_V2_Thumbstick,
                    SteamVR_Actions.default_Bool_ButtonA,
                    SteamVR_Actions.default_Bool_ButtonB,
                    SteamVR_Actions.default_Bool_ButtonX,
                    SteamVR_Actions.default_Bool_ButtonY,
                    SteamVR_Actions.default_Bool_ThumbstickUp,
                    SteamVR_Actions.default_Bool_ThumbstickDown,
                    SteamVR_Actions.default_Bool_ThumbstickLeft,
                    SteamVR_Actions.default_Bool_ThumbstickRight,
                    SteamVR_Actions.default_Bool_Trigger,
                    SteamVR_Actions.default_Bool_Grip,
                    SteamVR_Actions.default_V1_Trigger,
                    SteamVR_Actions.default_V1_Grip,
                    SteamVR_Actions.default_Bool_ButtonThumbstick};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create <SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create <SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create <SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_V2_Thumbstick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create <SteamVR_Action_Vector2>("/actions/default/in/V2_Thumbstick")));
            SteamVR_Actions.p_default_Bool_ButtonA = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_ButtonA")));
            SteamVR_Actions.p_default_Bool_ButtonB = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_ButtonB")));
            SteamVR_Actions.p_default_Bool_ButtonX = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_ButtonX")));
            SteamVR_Actions.p_default_Bool_ButtonY = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_ButtonY")));
            SteamVR_Actions.p_default_Bool_ThumbstickUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_ThumbstickUp")));
            SteamVR_Actions.p_default_Bool_ThumbstickDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_ThumbstickDown")));
            SteamVR_Actions.p_default_Bool_ThumbstickLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_ThumbstickLeft")));
            SteamVR_Actions.p_default_Bool_ThumbstickRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_ThumbstickRight")));
            SteamVR_Actions.p_default_Bool_Trigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_Trigger")));
            SteamVR_Actions.p_default_Bool_Grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_Grip")));
            SteamVR_Actions.p_default_V1_Trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create <SteamVR_Action_Single>("/actions/default/in/V1_Trigger")));
            SteamVR_Actions.p_default_V1_Grip = ((SteamVR_Action_Single)(SteamVR_Action.Create <SteamVR_Action_Single>("/actions/default/in/V1_Grip")));
            SteamVR_Actions.p_default_Bool_ButtonThumbstick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/default/in/Bool_ButtonThumbstick")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create <SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
        }
    }
}
